# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

serverConfig:
    node.environment: test
    http-server.http.port: 8080

presetUsers:
  admin:
    password: admin
    privileges: ADMIN_USER

dataStore:
  #This stores the URLs of backend Trino servers and query history
  jdbcUrl: jdbc:postgresql://localhost:5432/gateway
  user: postgres
  password: mysecretpassword
  driver: org.postgresql.Driver

clusterStatsConfiguration:
  monitorType: INFO_API
